### ISSUE TITLE
Please register this library at platform.io

### ISSUE THREAD

**Issue by cyberman54** [lewisxhe/XPowersLib#1]
Thanks!

**Comment by lewisxhe** [comment]
I have already registered earlier, can't I search?

![image](https://user-images.githubusercontent.com/22990954/185603640-7f5ec01d-2fa2-4936-9076-85eece9908dd.png)

**Comment by cyberman54** [comment]
Yes, thank you, it works - if searching for "xpowerslib", i searched for "xpowers" it seems platformio then don't match.
Thanks for this library, i migrated my app from your previous AXP202 library to this new one, and now all flaws seen with PEK key are gone.
