### ISSUE TITLE
help with AXP2101 begin or init

### ISSUE THREAD

**Issue by richonguzman** [lewisxhe/XPowersLib#10]
Hi,

I'm trying to init/begin the chip AXP2101 of the new T-Beam V1.2 

#define I2C_SDA 21
#define I2C_SCL 22
bool result = PMU.begin(Wire, AXP2101_SLAVE_ADDRESS, I2C_SDA, I2C_SCL);

results always returns 1 , which I asume is "not" begin successful, right?

**Comment by lyusupov** [comment]
https://github.com/lewisxhe/XPowersLib/blob/master/examples/AXP2101_Example/AXP2101_Example.ino
