### ISSUE TITLE
Default voltage and Startup Sequence?

### ISSUE THREAD

**Issue by khoa21214475** [lewisxhe/XPowersLib#11]
[AXP2101.pdf](https://github.com/lewisxhe/XPowersLib/files/12512115/AXP2101.pdf)
Is it true that the first time it starts, the DCDC1 voltage will be 3.3 Vdc according to section 7.6 of the datasheet I attached? How will the starting order of the voltages be configured? I don't see instructions in the documentation.
Please help me!

**Comment by lewisxhe** [comment]
Already replied in other repositories
