### ISSUE TITLE
Is there an equivalent to AXP192's getBatteryChargeCurrent and getVbusCurrent in AXP2101?

### ISSUE THREAD

**Issue by HouzuoGuo** [lewisxhe/XPowersLib#12]
Hey! I'm porting my ttgo t-beam's code to run on the newer model with AXP2101. For AXP192 I've got these lines of code reading the current consumption:

```
status.batt_milliamp = pmu->getBatteryChargeCurrent();
status.batt_milliamp = -pmu->getBattDischargeCurrent();
status.power_draw_milliamp = pmu->getVbusCurrent();
```

Is there an equivalent for AXP2101?

Thanks.

**Comment by lewisxhe** [comment]
AXP2101 does not have this function, only AXP192 has it
