### ISSUE TITLE
Equivalent of AXP202 library

### ISSUE THREAD

**Issue by NDC-SC** [lewisxhe/XPowersLib#15]
Is there an equivalent library for a battery powered ESP32-S3 to the AXP202 library for the TTGO T-Watch.
Currant usage could be measured without a device, such as an INA219 module.
The getBattChargeCurrent() and getBattDischargeCurrent() function are very useful.

**Comment by lewisxhe** [comment]
What you should be talking about is AXP2101, which does not have a discharge current measurement function. Isn’t there a lot of libraries available on IN219 github?

**Comment by NDC-SC** [comment]
The advantage of the power management library for the TTGO T-Watch is that an external INA219 module is not required.
Is there a comparable power management library for the ESP32-S3 ?
