### ISSUE TITLE
AXP2101 using PWRON as EN mode

### ISSUE THREAD

**Issue by gfilippi** [lewisxhe/XPowersLib#16]
Hello, from the datasheet I read that the AXP2101 pin for EX/PWRON can be configured as "enable pin" so that we do not need the PWRKEY to be pressed every time.

from the library it is not clear to me how to setup the PMU so that it will simply turn on/off using the pin as an ENABLE signal.

could you please help ?

thanks

**Comment by lewisxhe** [comment]
This is a chip customization function. It has been configured when the chip leaves the factory and cannot be changed through software.
