### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by mathieucarbou** [lewisxhe/XPowersLib#20]
Would it be possible to release the new changes and `pio pkg publish` them ?
Thanks!

**Comment by lewisxhe** [comment]
Of course, but wouldn't esp32 also be indexed into espressif?

**Comment by mathieucarbou** [comment]
No for ESPIDF projects this is yet another repo. I was more asking of a new tag and new deployment in platformio repo: https://registry.platformio.org/libraries/lewisxhe/XPowersLib

**Comment by lewisxhe** [comment]
Okay, it has been published. It will be indexed in a moment.

**Comment by lewisxhe** [comment]
![image](https://github.com/lewisxhe/XPowersLib/assets/22990954/b84b1c2b-d4df-4a36-be49-e9997e42a6ed)

Done .

**Comment by mathieucarbou** [comment]
Thanks a lot :-)
FYI I m working on this project which makes use of the new lilyfo boards and XPower lib and your TinyGSM fork: https://beelance.carbou.me

**Comment by lewisxhe** [comment]
Cool project, thanks for sharing
