### ISSUE TITLE
Temperature function for AXP 2101 

### ISSUE THREAD

**Issue by LakinduBabySoap** [lewisxhe/XPowersLib#24]
Hello, firstly thank you for creating and managing this library. It has been very helpful to track these parameters of the microcontrollers.

I have 2 T-Beams, one with the AXP192 and one with AXP 2101. My aim is to retrieve if the T-Beam is charging, temperature, battery voltage and percentage and forward it to TTN. For the AXP192, I can see all these parameters but for AXP2101, the example does not show how to retrieve temperature data.

However, when I add the statement ```PMU.getBattVoltage()``` and print it out and send it to ttn, it produces a faulty value. For example. it returns temperature as 58.2 degrees when it should be in the 30s range. Is this function not configured for the AXP2101?

Thank you.

**Comment by lewisxhe** [comment]
See example [AXP2101_ADC_Example](https://github.com/lewisxhe/XPowersLib/blob/master/examples/AXP2101_ADC_Example/AXP2101_ADC_Example.ino)

**Comment by LakinduBabySoap** [comment]
> See example [AXP2101_ADC_Example](https://github.com/lewisxhe/XPowersLib/blob/master/examples/AXP2101_ADC_Example/AXP2101_ADC_Example.ino)

Thank you for the reply. Unfortunately, when I run the program, it produces this error on loop.
```
invalid header: 0x61259440
invalid he�ets Jul 29 2019 12:21:46

rst:0x7 (TG0WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
invalid header: 0x61259440
invalid header: 0x61259440
```

I have run the ADC 2101 Example without any issue. Would appreciate if you can check this? I am not sure if it is a problem with the device.

Thank you.

**Comment by lewisxhe** [comment]
Of course it is normal. The error is caused by selecting the wrong option in Arduino IDE. This example is for reference of another [esp32S3](https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/issues/27) . Everything is normal.
![image](https://github.com/user-attachments/assets/8252ef15-ea27-416f-9c2b-e9d8641d50f5)

**Comment by LakinduBabySoap** [comment]
> Of course it is normal. The error is caused by selecting the wrong option in Arduino IDE. This example is for reference of another [esp32S3](https://github.com/Xinyuan-LilyGO/LilyGo-T-SIM7080G/issues/27) . Everything is normal. ![image](https://private-user-images.githubusercontent.com/22990954/356791679-8252ef15-ea27-416f-9c2b-e9d8641d50f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTI3NjQsIm5iZiI6MTcyMzY5MjQ2NCwicGF0aCI6Ii8yMjk5MDk1NC8zNTY3OTE2NzktODI1MmVmMTUtZWEyNy00MTZmLTljMmItZTlkODY0MWQ1MGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAzMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MWVhZWU3ZDEzZjBiMDNmZWU1MjVmZjdiYWQyYzllZDkxZGE3N2FiNTRlZTJlZTY5MDE0YzUxYTcxNzllNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K7WTTHbxHmkrNetLTR-Q0VkOqP8XvaeD3uf1cFKIPQM)

Apologies for the late reply. I changed the pin configurations of the code and now it works perfectly fine. You can close the issue.

Thanks!
