### ISSUE TITLE
wrong string

### ISSUE THREAD

**Issue by DevAnyKR** [lewisxhe/XPowersLib#29]
Arduino IDE - Library - XPowerLib - 0.2.6

https://github.com/lewisxhe/XPowersLib/blob/master/examples/AXP2101_Example/AXP2101_Example.ino

Wrong: getDCHighVoltagePowerDownEn();   // Build Error.
Correct: getDCHighVoltagePowerDowmEn(); // Build Success.

so,,,what is mean 'Dowm' ?

**Comment by lewisxhe** [comment]
This issue has been fixed here
https://github.com/lewisxhe/XPowersLib/commit/f608c0a1123cbeebf4a07eed71953b7710b1d18a

**Comment by DevAnyKR** [comment]
ok, it just release to 0.2.7. I'll wait for Arduino to update too.
