### ISSUE TITLE
Are AXP2101 and AXP2102 the same?

### ISSUE THREAD

**Issue by LeonardoCT** [lewisxhe/XPowersLib#7]
Hello, i'm trying to compile some examples and when i open the "AXP2101_Example" right at the start the file i see:
```c++
// Defined using AXP2102
#define XPOWERS_CHIP_AXP2102
``` 
And if i try to use:
```c++
#define XPOWERS_CHIP_AXP2101
``` 
it doesn't exist, so do AXP2101 and AXP2102 use the same protocol and can be used interchangeably? or i'm just a dummy?

**Comment by lewisxhe** [comment]
Thank you, this is an error caused by copy and paste, it has been modified
