### ISSUE TITLE
Please update lib 0.1.6 in platform.io

### ISSUE THREAD

**Issue by cyberman54** [lewisxhe/XPowersLib#8]
Platform.io still shows v0.1.5, seems it need a kick to pull in the current v0.1.6

**Comment by lewisxhe** [comment]
Unlike before, Pio does not update the registry through a crawler. I need to report to the community to update the Pio registry. Please wait for a while

**Comment by cyberman54** [comment]
You can update yourself by using pio pkg publish command. See
https://docs.platformio.org/en/stable/core/userguide/pkg/cmd_publish.html

**Comment by lewisxhe** [comment]
I've tried this and I can't make a commit. That's why I need to ask the community for help

**Comment by lewisxhe** [comment]
@cyberman54  done
