### ISSUE TITLE
The library is not supported in pure C language

### ISSUE THREAD

**Issue by vabatta** [lewisxhe/XPowersLib#9]
Hi,

I've been trying to use the library in my project from PlatformIO (v0.1.7) but after having it included in my espidf pure C code, the compiler complains about `hpp` and `tpp` files (because they are actually not C friendly and cannot be compiled and included in a C project: see https://stackoverflow.com/questions/152555/h-or-hpp-for-your-class-definitions).

Can you please make it so it would be usable? Or is there an alternative to manage the PMU (I have T-7080G-S3) using other libs?

**Comment by lyusupov** [comment]
Example of use as ESP-IDF component:

This library _(earlier version)_ was included in the **Adafruit TinyUF2** project as an ESP32 'component' -
https://github.com/adafruit/tinyuf2/tree/master/ports/espressif/components

You may try to pick some hints there...
